name:                dprox
version:             0.4.1
github:              "bjin/dprox"
license:             BSD3
author:              "Bin Jin"
maintainer:          "bjin@ctrl-d.org"
copyright:           "2023 Bin Jin"

synopsis:            a lightweight DNS proxy server, compatible with dnsmasq-china-list
category:            DNS

description:
  Please see the README on GitHub at <https://github.com/bjin/dprox#readme>

extra-source-files:
- README.md
- systemd/dprox.service

dependencies:
- attoparsec >= 0.13
- base >= 4.12 && < 5
- bytestring >= 0.10
- bytestring-trie >= 0.2.4
- containers >= 0.6
- dns >= 3.0.4
- fast-logger >= 3.0
- hashable >= 1.2
- iproute >= 1.7
- network >= 2.8
- optparse-applicative >= 0.14
- psqueues >= 0.2.3
- streaming-commons >= 0.2
- time >= 1.8

flags:
  static:
    description: Enable static build
    manual: true
    default: false

default-extensions:
- ImportQualifiedPost

ghc-options:
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N

when:
- condition: flag(static)
  ghc-options: -optl-static -split-sections

executables:
  dprox:
    main:                Main.hs
    source-dirs:
    - src
    other-modules:
    - Config
    - DomainRoute
    - LRU
    - Log
    - Paths_dprox

tests:
  dprox-test:
    main:                Test.hs
    source-dirs:
    - src
    - test
    other-modules:
    - DomainRoute
    dependencies:
    - hspec
