name:                dprox
version:             0.2.0
github:              "bjin/dprox"
license:             BSD3
author:              "Bin Jin"
maintainer:          "bjin@ctrl-d.org"
copyright:           "2019 Bin Jin"

synopsis:            a lightweight DNS proxy server
category:            DNS

description:
  Please see the README on GitHub at <https://github.com/bjin/dprox#readme>

extra-source-files:
- README.md
- systemd/dprox.service

dependencies:
- attoparsec >= 0.13
- base >= 4.12 && < 5
- bytestring >= 0.10
- containers >= 0.6
- dns >= 3.0.4
- hashable >= 1.2
- iproute >= 1.7
- network >= 2.8
- optparse-applicative >= 0.14
- psqueues >= 0.2.3
- streaming-commons >= 0.2
- time >= 1.8
- unix >= 2.7
- unordered-containers >= 0.2

flags:
  static:
    description: Enable static build
    manual: true
    default: false

ghc-options:
- -Wall
- -O2
- -threaded
- -rtsopts
- -with-rtsopts=-N

when:
- condition: flag(static)
  ghc-options: -optl-static

executables:
  dprox:
    main:                Main.hs
    source-dirs:
    - src
    other-modules:
    - Config
    - DomainRoute
    - LRU
    - Paths_dprox

tests:
  dprox-test:
    main:                Test.hs
    source-dirs:
    - src
    - test
    other-modules:
    - DomainRoute
    dependencies:
    - hspec
